### ISSUE TITLE
i486 toolchain (and maybe others) fail with -fPIE -fstack-protector-all

### ISSUE THREAD

**Issue by rofl0r** [GregorR/musl-cross#45]
test.c
```c
int main() {return 0;}
```
```
i486-linux-musl-gcc test.c -fPIE -fstack-protector-all
/tmp/ccEkagdJ.o: In function `main':
test.c:(.text+0x28): undefined reference to `__stack_chk_fail_local'
/home/rofl/musl-cross-4.8.3/i486-linux-musl/lib/gcc/i486-linux-musl/4.8.3/../../../../i486-linux-musl/bin/ld: a.out: hidden symbol `__stack_chk_fail_local' isn't defined
/home/rofl/musl-cross-4.8.3/i486-linux-musl/lib/gcc/i486-linux-musl/4.8.3/../../../../i486-linux-musl/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
interestingly, the gcc build is aware of the need of libssp_nonshared.a and creates it from ssp-local.c, and it even installs it into lib/.
however, it fails to add it to its linker invocation when it's needed.

```
i486-linux-musl-gcc test.c -fPIE -fstack-protector-all -lssp_nonshared
```
works.
alpine linux uses the following patch for the same issue:
http://git.alpinelinux.org/cgit/aports/tree/main/gcc/gcc-4.8-musl-libssp.patch

**Comment by bradfa** [comment]
I've tested x86_64, mips, arm (hardfloat, v7a), and i486 with current git master (09bb1b927f9cf78194d0f198ebec17cf1640b7be).  Only i486 seems to have this compile-time issue.  I have not tested that the resulting binaries actually run.

For example, on the mips output, readelf shows:
```
 Global entries:
   Address     Access  Initial Sym.Val. Type    Ndx Name
  004109b0 -32720(gp) 00000000 00000000 FUNC    UND __register_frame_info
  004109b4 -32716(gp) 00000000 00000000 NOTYPE  UND _Jv_RegisterClasses
  004109b8 -32712(gp) 00400900 00400900 FUNC    UND __libc_start_main
  004109bc -32708(gp) 00000000 00000000 NOTYPE  UND _ITM_deregisterTMCloneTable
  004109c0 -32704(gp) 00000000 00000000 NOTYPE  UND _ITM_registerTMCloneTable
  004109c4 -32700(gp) 00000000 00000000 FUNC    UND __deregister_frame_info
  004109c8 -32696(gp) 004008f0 004008f0 FUNC    UND __stack_chk_fail
  004109cc -32692(gp) 00000000 00000000 OBJECT  UND __stack_chk_guard
```

I assume this is the desired result

**Comment by GregorR** [comment]
OK, the patch SEEMS harmless. ssp_nonshared shouldn't hurt if no-stack-protector is used, since it doesn't actually pull in anything *fingers crossed*. As such I've integrated the Alpine patch directly. Revision c57e607a5a5d of musl-cross.

**Comment by GregorR** [comment]
No, cancel that. I wasn't doing a full bootstrapping build to test (I already had the target directory filled). This patch breaks bootstrapping. This... is frustrating :). In the interest of getting something released, I'm just going to revoke the patch for 1.1.6. Reinvestigation required later.

**Comment by soul9** [comment]
this patch https://github.com/sabotage-linux/sabotage/blob/master/KEEP/gcc474-libssp_nonshared.patch doesn't break bootstrapping

**Comment by soul9** [comment]
While it does not break bootstrapping it introduces a bug where static linking fails with stack-protector. I am investigating.

**Comment by soul9** [comment]
With this and sabotage's musl patched I can bootstrap the cross-toolchain and build every package in sabotage stage1 with stack-protector-all, except gcc4.7.4 where I need to disable stack-protector entirely.

**Comment by soul9** [comment]
the libressl issue can be fixed by adding -lssp_nonshared to LDFLAGS. investigating further.

**Comment by GregorR** [comment]
Any conclusions?

**Comment by GregorR** [comment]
Oh, probably in that other ticket :)

**Comment by soul9** [comment]
and now at a third location too

**Comment by GregorR** [comment]
I like to spread the issue around :)
