### ISSUE TITLE
GCC 5.2.0 cross compile with musl1.1.10 build failure

### ISSUE THREAD

**Issue by bhanu1811** [GregorR/musl-cross#55]
Hi
I'm trying to build toolchain for my custom OS on ARM.
I hope that I have done all required changes. 
While compiling GCC 2nd stage, I get following build failure from libstdc++:

checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... immediate
checking for shl_load... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
gmake[1]: *** [configure-target-libstdc++-v3] Error 1

**Comment by rofl0r** [comment]
i remember this error and i fixed it like this
https://github.com/sabotage-linux/sabotage/blob/master/pkg/gcc530#L51

however it's not supposed to happen with vanilla musl-cross. i suspect it happens due to one of the changes you made in order to support "custom OS"

**Comment by GregorR** [comment]
I'm inclined to agree with rofl0r. This shouldn't happen with the default configuration, so it's probably a customization.
