### ISSUE TITLE
Where did the prebuilt toolchains go?

### ISSUE THREAD

**Issue by mzpqnxow** [GregorR/musl-cross#66]
This isn't quite directly related to this project, but the README mentions that http://musl.codu.org/ is the page for prebuilt toolchains and that https://bitbucket.org/GregorR/musl-cross/downloads/ is obsolete. Yet at the http://musl.codu.org/ site, there is only a broken link to a google hosted page.. are you still maintaining binary builds of musl toolchains or is that a thing of the past?

**Comment by rofl0r** [comment]
@GregorR has been busy lately; i don't think he is maintaining his binary builds anymore. the old binaries that are available at the bitbucket site should still work though; only their included musl libc copy is slightly outdated - but the crosscompiler itself can be user to compile musl again and then you can update the include/ and lib/ dirs in the crosscompiler's directory with the latest musl.
if that is not sufficient, i can upload the one or the other toolchain, but i don't really intend to continuously update a set of a dozen different crosscompilers for all the sub-arches.

**Comment by mzpqnxow** [comment]
Thanks, yeah no worries I already am maintaining 8 or 9 locally and just
found out about these.. thanks for the note

**Comment by rofl0r** [comment]
ftr there's now prebuilt toolchains available at http://musl.cc . i can't vouch for them just mentioning it.
